### ISSUE TITLE
calculate shipping cost based on shipment rates

### ISSUE THREAD

**Issue by Tapha** [jobizzness/sellox-sdk#1]
Shops have products. 

Products have weight.

The calculation for shipping weight * rate per location (within a zone).

- 
Previous implementation gets rates from setting within the product, instead of global rate. 

So now it needs to use the global rate rather than the product rate.

**Comment by jobizzness** [comment]
`export interface IShippingSettings {
  origin: {
    country: 'GM';
  };
  zones: [
    {
      subzones: [
        {
          location: 'kololi';
          label: 'Domestic';
          name: 'domestic';
          rates: [
            {
              weightUnit: 'pounds';
              range: '5 -> 10';
              flatRate: 50;
            }
          ];
        }
      ];
      country: '';
      label: 'Domestic';
      name: 'domestic';
      rates: [
        {
          weightUnit: 'pounds';
          range: '5 -> 10';
          flatRate: 50;
        }
      ];
    }
  ];
}
`

**Comment by jobizzness** [comment]
Temporary Interface for shipping settings @Tapha

**Comment by jobizzness** [comment]
![Capture](https://user-images.githubusercontent.com/14133399/82718168-598f2b00-9c90-11ea-8de6-378306844349.PNG)
